ALTER TABLE workshop_incidents
  ADD COLUMN IF NOT EXISTS status VARCHAR NOT NULL DEFAULT 'OPEN',
  ADD COLUMN IF NOT EXISTS diagnostic TEXT,
  ADD COLUMN IF NOT EXISTS intervention_note TEXT,
  ADD COLUMN IF NOT EXISTS responsible_comment TEXT,
  ADD COLUMN IF NOT EXISTS edit_request JSONB,
  ADD COLUMN IF NOT EXISTS delete_request BOOLEAN NOT NULL DEFAULT FALSE;
