ALTER TABLE admin_accounts
  ADD COLUMN IF NOT EXISTS notif_admin        BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS notif_responsables BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS notif_techniciens  BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS notif_operateurs   BOOLEAN NOT NULL DEFAULT TRUE;
